first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

first_project/main/urls.py
from django.urls import path
from . views import home_page, about_us ,contact_us,blog_detail
app_name = "blog"
urlpatterns = [
    path('', home_page,name = "home"),
    path('about_us', about_us,name = "about_us"),
    path('contact_us', contact_us,name = "contact_us"),
    path('blog-detail/<int:pk>',blog_detail,name = "blog-detail")
]

first_project/main/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    def ___str___(self):
        #db_colum = "{}{}".format(self.title,self.description)
        return self.title

first_project/main/views.py
from django.shortcuts import render
# Create your views here.
from django.http import HttpResponse
from .models import Blog


def home_page(request):
    context ={}
    blogs = Blog.objects.all()
    context['blogs']= blogs
    return render(request, "home.html", context)


def about_us(request):
    return render(request, "about_us.html", {})

def contact_us(request):
    return render(request, "contact_us.html", {})

def blog_detail(request,pk):
    print("------------")
    print("------------")

    context = {}
    blog = Blog.objects.get(id=pk)
    context['blog'] = blog
    return render(request, "blog_detail.html", context)

first_project/main/templates/about_us.html
{%extends 'base.html'%}

{%block content%}
<h1>"About as page"</h1>
{%endblock%}

first_project/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    .nav_class{
        list_style:none;
        color:red;
    }
    .nav_class > li {
    float:left;
    margin-right:10px;
    }


</style>
<body>
<header>
    <ul class="nav_class">
        <li><a href="{%url 'blog:home'%}">Home page</a></li>
        <li><a href="{%url 'blog:about_us'%}"> About us</a></li>
        <li><a href="{%url 'blog:contact_us'%}">Contac us</a></li>
    </ul>

</header>
<br>
{%block content%}
{%endblock%}
</body>
</html>

first_project/main/templates/blog_detail.html
{%extends 'base.html'%}

{%block content%}

<h1>{{blog.title}}</h1>
<h1>{{blog.description}}</h1>
{%endblock%}

first_project/main/templates/contact_us.html
{%extends 'base.html'%}

{%block content%}
<h1>"Contact as page"</h1>
{%endblock%}

first_project/main/templates/home.html
{%extends 'base.html'%}

{%block content%}
<h1>"Home page"</h1>

{%for blog in blogs%}
<p><a href="{%url 'blog:blog-detail' pk=blog.id %}"> {{blog.title}}</a></p>
{%endfor%}
{%endblock%}